In [191]:
import numpy as np
import pandas as pd

In [192]:
train=pd.read_csv('train_yaOffsB.csv')
train

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0      F00000001                      188          1          0   
1      F00000003                      209          1          0   
2      F00000004                      257          1          0   
3      F00000005                      257          1          1   
4      F00000006                      342          1          0   
...          ...                      ...        ...        ...   
88853  F00155935                     3337          1          0   
88854  F00155938                     3516          1          0   
88855  F00155939                     3516          1          0   
88856  F00155942                     3702          1          0   
88857  F00155945                     3895          1          0   

       Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                           1                  0                0.0   
1                           1                  0                0.0   
2                           1                  0                0.0   
3                           1                  0                0.0   
4                           1                  0                0.0   
...                       ...                ...                ...   
88853                       2                 10               12.0   
88854                       2                 10               20.0   
88855                       2                 15               40.0   
88856                       2                 10               25.0   
88857                       2                 20               37.0   

       Number_Weeks_Quit  Season  Crop_Damage  
0                      0       1            0  
1                      0       2            1  
2                      0       2            1  
3                      0       2            1  
4                      0       2            1  
...                  ...     ...          ...  
88853                 44       3            0  
88854                 38       1            0  
88855                  8       2            0  
88856                 18       3            0  
88857                  7       3            0  

[88858 rows x 10 columns]

In [193]:
train.drop('ID',axis=1,inplace=True)
train

Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
0                          188          1          0                       1   
1                          209          1          0                       1   
2                          257          1          0                       1   
3                          257          1          1                       1   
4                          342          1          0                       1   
...                        ...        ...        ...                     ...   
88853                     3337          1          0                       2   
88854                     3516          1          0                       2   
88855                     3516          1          0                       2   
88856                     3702          1          0                       2   
88857                     3895          1          0                       2   

       Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  \
0                      0                0.0                  0       1   
1                      0                0.0                  0       2   
2                      0                0.0                  0       2   
3                      0                0.0                  0       2   
4                      0                0.0                  0       2   
...                  ...                ...                ...     ...   
88853                 10               12.0                 44       3   
88854                 10               20.0                 38       1   
88855                 15               40.0                  8       2   
88856                 10               25.0                 18       3   
88857                 20               37.0                  7       3   

       Crop_Damage  
0                0  
1                1  
2                1  
3                1  
4                1  
...            ...  
88853            0  
88854            0  
88855            0  
88856            0  
88857            0  

[88858 rows x 9 columns]

In [194]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88858 entries, 0 to 88857
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Estimated_Insects_Count  88858 non-null  int64  
 1   Crop_Type                88858 non-null  int64  
 2   Soil_Type                88858 non-null  int64  
 3   Pesticide_Use_Category   88858 non-null  int64  
 4   Number_Doses_Week        88858 non-null  int64  
 5   Number_Weeks_Used        79858 non-null  float64
 6   Number_Weeks_Quit        88858 non-null  int64  
 7   Season                   88858 non-null  int64  
 8   Crop_Damage              88858 non-null  int64  
dtypes: float64(1), int64(8)
memory usage: 6.1 MB


In [195]:
train['Number_Weeks_Used'].value_counts()

20.0    3878
30.0    3765
25.0    3120
40.0    2707
15.0    2486
        ... 
63.0      50
64.0      44
65.0      31
66.0      17
67.0       8
Name: Number_Weeks_Used, Length: 64, dtype: int64

In [196]:
a=train[train['Pesticide_Use_Category']==1]

In [197]:
a

Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
0                          188          1          0                       1   
1                          209          1          0                       1   
2                          257          1          0                       1   
3                          257          1          1                       1   
4                          342          1          0                       1   
...                        ...        ...        ...                     ...   
86351                     3336          0          1                       1   
86352                     3337          0          1                       1   
86353                     3337          1          0                       1   
86354                     3895          1          1                       1   
86355                     4096          1          0                       1   

       Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  \
0                      0                0.0                  0       1   
1                      0                0.0                  0       2   
2                      0                0.0                  0       2   
3                      0                0.0                  0       2   
4                      0                0.0                  0       2   
...                  ...                ...                ...     ...   
86351                  0                NaN                  0       1   
86352                  0                0.0                  0       2   
86353                  0                NaN                  0       1   
86354                  0                0.0                  0       3   
86355                  0                0.0                  0       2   

       Crop_Damage  
0                0  
1                1  
2                1  
3                1  
4                1  
...            ...  
86351            2  
86352            2  
86353            2  
86354            1  
86355            2  

[837 rows x 9 columns]

In [198]:
a['Number_Weeks_Used']=a['Number_Weeks_Used'].fillna(0)

C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [199]:
a.isnull().sum()

Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
Crop_Damage                0
dtype: int64

In [200]:
b=train[train['Pesticide_Use_Category']==2]

In [201]:
b

Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
707                        169          0          0                       2   
708                        232          0          0                       2   
709                        256          0          0                       2   
710                        312          0          0                       2   
711                        311          0          0                       2   
...                        ...        ...        ...                     ...   
88853                     3337          1          0                       2   
88854                     3516          1          0                       2   
88855                     3516          1          0                       2   
88856                     3702          1          0                       2   
88857                     3895          1          0                       2   

       Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  \
707                   30                NaN                  1       2   
708                   20                NaN                  9       2   
709                   20               14.0                  0       2   
710                   35               26.0                  1       2   
711                   60               20.0                  4       1   
...                  ...                ...                ...     ...   
88853                 10               12.0                 44       3   
88854                 10               20.0                 38       1   
88855                 15               40.0                  8       2   
88856                 10               25.0                 18       3   
88857                 20               37.0                  7       3   

       Crop_Damage  
707              0  
708              0  
709              0  
710              0  
711              0  
...            ...  
88853            0  
88854            0  
88855            0  
88856            0  
88857            0  

[63709 rows x 9 columns]

In [202]:
b['Number_Weeks_Used']=b['Number_Weeks_Used'].fillna(b['Number_Weeks_Used'].median())

C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [203]:
b.isnull().sum()

Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
Crop_Damage                0
dtype: int64

In [204]:
c=train[train['Pesticide_Use_Category']==3]

In [205]:
c['Number_Weeks_Used']=c['Number_Weeks_Used'].fillna(c['Number_Weeks_Used'].median())

C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [206]:
c.isnull().sum()

Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
Crop_Damage                0
dtype: int64

In [207]:
df=pd.concat([a,b,c],axis=0)
df

Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
0                          188          1          0                       1   
1                          209          1          0                       1   
2                          257          1          0                       1   
3                          257          1          1                       1   
4                          342          1          0                       1   
...                        ...        ...        ...                     ...   
87071                     3702          1          1                       3   
87072                     3895          1          0                       3   
87073                     3895          1          1                       3   
87074                     4096          1          0                       3   
87075                     4096          1          1                       3   

       Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  \
0                      0                0.0                  0       1   
1                      0                0.0                  0       2   
2                      0                0.0                  0       2   
3                      0                0.0                  0       2   
4                      0                0.0                  0       2   
...                  ...                ...                ...     ...   
87071                  5               50.0                  0       3   
87072                 20               55.0                  0       1   
87073                 20               55.0                  0       3   
87074                  5               40.0                  0       1   
87075                  5               50.0                  0       1   

       Crop_Damage  
0                0  
1                1  
2                1  
3                1  
4                1  
...            ...  
87071            1  
87072            0  
87073            0  
87074            1  
87075            0  

[88858 rows x 9 columns]

In [208]:
df.isnull().sum()

Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
Crop_Damage                0
dtype: int64

In [209]:
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

In [210]:
x = df.drop(columns='Crop_Damage')
y = df.Crop_Damage

In [211]:
x.shape

(88858, 8)

In [212]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [147]:
from sklearn.linear_model import LogisticRegression
model =LogisticRegression()
model.fit(X_train,y_train)


C:\Users\HP\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [33]:
def evaluation_train_test(model,X_train,y_train,X_test,y_test):
    y_train_prob = model.predict_proba(X_train)[:,1]
    y_train_pred = model.predict(X_train)
    y_test_prob = model.predict_proba(X_test)[:,1]
    y_test_pred = model.predict(X_test)
    from sklearn.metrics import confusion_matrix,accuracy_score,roc_auc_score,roc_curve,classification_report
    print('Train accuracy score for train of',model,':',accuracy_score(y_train,y_train_pred))
    print('Test accuracy score for test of ',model,':',accuracy_score(y_test,y_test_pred))
    
   
    print('Train classification report \n',classification_report(y_train,y_train_pred))
    print('Test classification report \n',classification_report(y_test,y_test_pred))

In [148]:
    y_train_prob = model.predict_proba(X_train)[:,1]
    y_train_pred = model.predict(X_train)
    y_test_prob = model.predict_proba(X_test)[:,1]
    y_test_pred = model.predict(X_test)
    from sklearn.metrics import confusion_matrix,accuracy_score,roc_auc_score,roc_curve,classification_report
    print('Train accuracy score for train of',model,':',accuracy_score(y_train,y_train_pred))
    print('Test accuracy score for test of ',model,':',accuracy_score(y_test,y_test_pred))
    
   
    print('Train classification report \n',classification_report(y_train,y_train_pred))
    print('Test classification report \n',classification_report(y_test,y_test_pred))

Train accuracy score for train of LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False) : 0.8361776463869386
Test accuracy score for test of  LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False) : 0.837948438139408
Train classification report 
               precision    recall  f1-score   support

           0       0.84      1.00      0.91     49705
           1       0.49      0.03      0.07      8293
           2       0.00      0.00      0.00    

C:\Users\HP\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [34]:
evaluation_train_test(lr,X_train,y_train,X_test,y_test)

Train accuracy score for train of LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False) : 0.857577182786307
Test accuracy score for test of  LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False) : 0.8593643432001091
Train classification report 
               precision    recall  f1-score   support

           0       0.88      1.00      0.93     49705
           1       0.58      0.17      0.26      8293
           2       0.23      0.08      0.12    

In [37]:
from sklearn.ensemble import RandomForestClassifier
rfc= RandomForestClassifier()
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint as sp_randint
params={'n_estimators':sp_randint(5,150), 'max_features':sp_randint(1,8),'max_depth':sp_randint(2,10),'min_samples_leaf':sp_randint(1,50),'min_samples_split':sp_randint(2,50),'criterion':['gini','entropy']}
rsearch=RandomizedSearchCV(rfc,param_distributions=params,n_jobs=-1,scoring='accuracy',n_iter=100,cv=3)
rsearch.fit(x,y)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=1)
rfc= RandomForestClassifier(**rsearch.best_params_)
rfc.fit(X_train,y_train)
from sklearn.metrics import confusion_matrix, accuracy_score, roc_auc_score, roc_curve, classification_report
y_train_pred=rfc.predict(X_train)
#y_train_prob=rfc.predict_proba(X_train)[:,1]
print('Accuracy score of train: ', accuracy_score(y_train,y_train_pred))
print('Confusion Matrix of train: ', confusion_matrix(y_train,y_train_pred))
#print('Auc of train: ', roc_auc_score(y_train,y_train_prob))
y_test_pred=rfc.predict(X_test)
#y_test_prob=rfc.predict_proba(X_test)[:,1]
print('Accuracy score of test: ', accuracy_score(y_test,y_test_pred))
print('Confusion Matrix of test: ', confusion_matrix(y_test,y_test_pred))
#print('Auc of test: ', roc_auc_score(y_test,y_test_prob))

Accuracy score of train:  0.8361414790996785
Confusion Matrix of train:  [[52008     0     0]
 [ 8594     0     0]
 [ 1598     0     0]]
Accuracy score of test:  0.8338960162052668
Confusion Matrix of test:  [[22230     0     0]
 [ 3713     0     0]
 [  715     0     0]]


In [39]:
from lightgbm import LGBMClassifier
lgb=LGBMClassifier()
lgb.fit(X_train,y_train)
y_train_pred=lgb.predict(X_train)
y_train_prob=lgb.predict_proba(X_train)[:,1]

print('Accuracy score of train: ', accuracy_score(y_train,y_train_pred))
print('Confusion Matrix of train: ', confusion_matrix(y_train,y_train_pred))
#print('Auc of train: ', roc_auc_score(y_train,y_train_prob))

y_test_pred=lgb.predict(X_test)
y_test_prob=lgb.predict_proba(X_test)[:,1]
print('Accuracy score of test: ', accuracy_score(y_test,y_test_pred))
print('Confusion Matrix of test: ', confusion_matrix(y_test,y_test_pred))
#print('Auc of test: ', roc_auc_score(y_test,y_test_prob))
print('Test: ',classification_report(y_test,y_test_pred))

Accuracy score of train:  0.8513826366559486
Confusion Matrix of train:  [[51324   684     0]
 [ 6963  1631     0]
 [ 1124   473     1]]
Accuracy score of test:  0.8442868932403031
Confusion Matrix of test:  [[21887   343     0]
 [ 3093   620     0]
 [  512   203     0]]
Test:                precision    recall  f1-score   support

           0       0.86      0.98      0.92     22230
           1       0.53      0.17      0.25      3713
           2       0.00      0.00      0.00       715

    accuracy                           0.84     26658
   macro avg       0.46      0.38      0.39     26658
weighted avg       0.79      0.84      0.80     26658



C:\Users\HP\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [149]:
test=pd.read_csv('test_pFkWwen.csv')
test

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0      F00000002                      188          1          1   
1      F00000007                      410          1          1   
2      F00000011                      626          1          0   
3      F00000013                      731          1          0   
4      F00000014                      789          0          0   
...          ...                      ...        ...        ...   
59305  F00155937                     3337          1          0   
59306  F00155940                     3516          1          0   
59307  F00155941                     3702          1          0   
59308  F00155943                     3702          1          0   
59309  F00155944                     3895          1          0   

       Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                           1                  0                NaN   
1                           1                  0                0.0   
2                           1                  0                0.0   
3                           1                  0                0.0   
4                           1                  0                0.0   
...                       ...                ...                ...   
59305                       2                 20               34.0   
59306                       2                 20               32.0   
59307                       2                 10                NaN   
59308                       2                 10               28.0   
59309                       2                  5               52.0   

       Number_Weeks_Quit  Season  
0                      0       2  
1                      0       2  
2                      0       2  
3                      0       2  
4                      0       1  
...                  ...     ...  
59305                 12       1  
59306                 10       2  
59307                 48       1  
59308                 17       2  
59309                  7       1  

[59310 rows x 9 columns]

In [150]:
a=test[test['Pesticide_Use_Category']==1]

In [151]:
a

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0      F00000002                      188          1          1   
1      F00000007                      410          1          1   
2      F00000011                      626          1          0   
3      F00000013                      731          1          0   
4      F00000014                      789          0          0   
...          ...                      ...        ...        ...   
57606  F00151495                     1212          1          1   
57607  F00151498                     1385          1          0   
57608  F00151501                     1575          1          1   
57609  F00151504                     2267          0          0   
57610  F00151511                     3164          0          0   

       Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                           1                  0                NaN   
1                           1                  0                0.0   
2                           1                  0                0.0   
3                           1                  0                0.0   
4                           1                  0                0.0   
...                       ...                ...                ...   
57606                       1                  0                NaN   
57607                       1                  0                0.0   
57608                       1                  0                0.0   
57609                       1                  0                0.0   
57610                       1                  0                0.0   

       Number_Weeks_Quit  Season  
0                      0       2  
1                      0       2  
2                      0       2  
3                      0       2  
4                      0       1  
...                  ...     ...  
57606                  0       2  
57607                  0       2  
57608                  0       2  
57609                  0       3  
57610                  0       2  

[571 rows x 9 columns]

In [152]:
a['Number_Weeks_Used']=a['Number_Weeks_Used'].fillna(0)

C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [153]:
a.isnull().sum()

ID                         0
Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
dtype: int64

In [154]:
b=test[test['Pesticide_Use_Category']==2]

In [155]:
b

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
504    F00001272                      151          0          0   
505    F00001274                      209          0          0   
506    F00001277                      256          0          0   
507    F00001278                      283          0          0   
508    F00001279                      283          0          0   
...          ...                      ...        ...        ...   
59305  F00155937                     3337          1          0   
59306  F00155940                     3516          1          0   
59307  F00155941                     3702          1          0   
59308  F00155943                     3702          1          0   
59309  F00155944                     3895          1          0   

       Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
504                         2                 40               18.0   
505                         2                 20               21.0   
506                         2                 20                NaN   
507                         2                 15               14.0   
508                         2                 20               20.0   
...                       ...                ...                ...   
59305                       2                 20               34.0   
59306                       2                 20               32.0   
59307                       2                 10                NaN   
59308                       2                 10               28.0   
59309                       2                  5               52.0   

       Number_Weeks_Quit  Season  
504                    2       2  
505                    4       2  
506                    3       1  
507                   11       2  
508                    6       2  
...                  ...     ...  
59305                 12       1  
59306                 10       2  
59307                 48       1  
59308                 17       2  
59309                  7       1  

[42556 rows x 9 columns]

In [156]:
b['Number_Weeks_Used']=b['Number_Weeks_Used'].fillna(b['Number_Weeks_Used'].median())

C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [157]:
b.isnull().sum()

ID                         0
Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
dtype: int64

In [158]:
c=test[test['Pesticide_Use_Category']==3]

In [159]:
c['Number_Weeks_Used']=c['Number_Weeks_Used'].fillna(c['Number_Weeks_Used'].median())

C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [160]:
c.isnull().sum()

ID                         0
Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
dtype: int64

In [161]:
df1=pd.concat([a,b,c],axis=0)
df1

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0      F00000002                      188          1          1   
1      F00000007                      410          1          1   
2      F00000011                      626          1          0   
3      F00000013                      731          1          0   
4      F00000014                      789          0          0   
...          ...                      ...        ...        ...   
58077  F00152755                     3337          1          0   
58078  F00152761                     3337          1          1   
58079  F00152765                     3516          1          1   
58080  F00152767                     3702          1          1   
58081  F00152768                     3895          1          0   

       Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                           1                  0                0.0   
1                           1                  0                0.0   
2                           1                  0                0.0   
3                           1                  0                0.0   
4                           1                  0                0.0   
...                       ...                ...                ...   
58077                       3                 40               58.0   
58078                       3                 10               49.0   
58079                       3                 15               47.0   
58080                       3                 10               44.0   
58081                       3                 10               35.0   

       Number_Weeks_Quit  Season  
0                      0       2  
1                      0       2  
2                      0       2  
3                      0       2  
4                      0       1  
...                  ...     ...  
58077                  0       2  
58078                  0       1  
58079                  0       1  
58080                  0       1  
58081                  0       1  

[59310 rows x 9 columns]

In [162]:
df1.isnull().sum()

ID                         0
Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
dtype: int64

In [163]:
df2=df1.drop(['ID'],axis=1)

In [165]:
y_test_pred =lgb.predict(df2)

In [167]:
submission=pd.DataFrame()
submission["ID"]=test["ID"]
submission["Crop_Damage"]=y_test_pred

In [168]:
submission.to_csv("Submission.csv")